export class FederalProgramsHelper {
  public static getSeedPrograms(): Record<string, unknown>[] {
    return [
      {
        sourceId: 'seed-nasa-sbir-sttr',
        source: 'seed',
        title: 'NASA SBIR/STTR Program',
        description:
          'NASA funds small businesses to mature technologies the agency needs for its science, exploration, and aeronautics missions. Topic areas include in-space and advanced manufacturing, composites and lightweight metallic structures, additive manufacturing, propulsion, autonomy, avionics, sensors, and space communications. Awards are issued as contracts under an annual solicitation; Phase I is a short feasibility effort and Phase II is a full prototype development effort. STTR requires a partnership with a US research institution.',
        agency: 'National Aeronautics and Space Administration',
        agencyCode: 'NASA',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        isSttr: true,
        naicsCodes: ['336411', '336412', '336413', '336414', '336415', '326199', '541715'],
        keywords: [
          'in-space manufacturing',
          'advanced manufacturing',
          'additive manufacturing',
          'composites',
          'lightweight metals',
          'propulsion',
          'avionics',
          'sensors',
          'autonomy',
          'space technology',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.nasa.gov/sbir_sttr/',
        provenance: {
          sourceUrl: 'https://www.nasa.gov/sbir_sttr/',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record. sbir.gov was returning 403 during scheduled maintenance, so this program could not be ingested from a live solicitation feed. Award amounts intentionally omitted because no NASA-specific figure is documented in our research reference.',
        },
      },
      {
        sourceId: 'seed-dod-sbir-sttr',
        source: 'seed',
        title: 'DoD SBIR/STTR Program (DSIP)',
        description:
          'The Department of Defense runs the largest SBIR/STTR program in the federal government across the Air Force, Space Force, Army, Navy, DARPA, DIU, and defense agencies. Solicitations run in rolling cycles through the Defense SBIR/STTR Innovation Portal and mix conventional topics, where a program office defines the requirement, with open topics, where the company proposes the problem and names a government end user. Technology areas span autonomy, artificial intelligence, cybersecurity, microelectronics, advanced materials and manufacturing, sensors, space systems, and human performance. Awards are contracts, and Direct-to-Phase-II entry is available where prior feasibility work can be shown.',
        agency: 'U.S. Department of Defense',
        agencyCode: 'DOD',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        isSttr: true,
        minAward: 75000,
        maxAward: 2000000,
        naicsCodes: ['541512', '541511', '541519', '541690', '541715', '334511', '336414'],
        keywords: [
          'defense',
          'dual-use',
          'autonomy',
          'artificial intelligence',
          'cybersecurity',
          'microelectronics',
          'advanced materials',
          'sensors',
          'open topic',
          'direct to phase ii',
        ],
        status: 'posted',
        curated: true,
        provenance: {
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record. sbir.gov and dodsbirsttr.mil both returned 403 at verification time, so no public program URL is attached rather than shipping a dead link. Award band $75K-$2M reflects the DoD SBIR figures in our research reference (Phase I $75K-$295K, Phase II up to $1.8-2M).',
        },
      },
      {
        sourceId: 'seed-afwerx-open-topic',
        source: 'seed',
        title: 'AFWERX Open Topic SBIR/STTR (U.S. Air Force)',
        description:
          'AFWERX runs the Air Force SBIR/STTR program and its Open Topic track, where a company proposes its own dual-use technology instead of responding to a predefined requirement. An Open Topic proposal requires a named Air Force end user who has documented interest in the capability, which makes customer discovery part of the application rather than an afterthought. Phase I is a short feasibility and customer-validation effort; Phase II funds prototype development and field evaluation. Direct-to-Phase-II is available for technologies with prior feasibility evidence.',
        agency: 'U.S. Air Force (AFWERX)',
        agencyCode: 'DOD',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        isSttr: true,
        programPhase: 'I',
        minAward: 75000,
        maxAward: 295000,
        naicsCodes: ['541512', '541511', '541715', '334511', '336411', '336413'],
        keywords: [
          'open topic',
          'air force',
          'dual-use',
          'end user memo',
          'prototype',
          'autonomy',
          'counter-uas',
          'imaging',
          'advanced manufacturing',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.afwerx.com/sbir-sttr/',
        provenance: {
          sourceUrl: 'https://www.afwerx.com/sbir-sttr/',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov solicitations API was 403 during maintenance. Phase I band $75K-$295K per our research reference (AFWERX Open Topic ~$75K SBIR / ~$110K STTR at the low end). No close date is recorded because cycle dates were not verifiable at seed time.',
        },
      },
      {
        sourceId: 'seed-spacewerx',
        source: 'seed',
        title: 'SpaceWERX SBIR/STTR (U.S. Space Force)',
        description:
          'SpaceWERX is the innovation arm of the U.S. Space Force and runs Space Force SBIR/STTR topics, including Open Topic cycles and focused challenges such as Orbital Prime. Technology interests include on-orbit servicing and mobility, space domain awareness, resilient space communications, propulsion, spacecraft components and materials, and ground-segment software. Awards are contracts and follow the same Phase I / Phase II / Direct-to-Phase-II structure as the rest of the Department of the Air Force program. Proposals generally need an identified Space Force or Guardian end user.',
        agency: 'U.S. Space Force (SpaceWERX)',
        agencyCode: 'DOD',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        isSttr: true,
        minAward: 75000,
        maxAward: 2000000,
        naicsCodes: ['336414', '336415', '336419', '334511', '541715', '541512'],
        keywords: [
          'space force',
          'on-orbit servicing',
          'space domain awareness',
          'satellite',
          'propulsion',
          'spacecraft components',
          'orbital prime',
          'open topic',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.spacewerx.us/',
        provenance: {
          sourceUrl: 'https://www.spacewerx.us/',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov was 403 during maintenance. Award band uses the DoD SBIR figures in our research reference (Phase I $75K-$295K, Phase II up to $1.8-2M), which that reference groups across AFWERX/SpaceWERX.',
        },
      },
      {
        sourceId: 'seed-stratfi-tacfi',
        source: 'seed',
        title: 'STRATFI / TACFI — Strategic and Tactical Funding Increase',
        description:
          'STRATFI and TACFI are Department of the Air Force supplemental funding vehicles that bridge the gap between a Phase II SBIR and a program of record. They add SBIR dollars on top of matched government program funding and private investment, so the total package can be several times the SBIR contribution. Eligibility is limited to companies with an active or recently completed Phase II and a program office willing to commit matching funds. These vehicles are how a small business reaches award sizes that a single SBIR Phase II cannot cover.',
        agency: 'U.S. Air Force (AFWERX)',
        agencyCode: 'DOD',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        programPhase: 'II',
        minAward: 3000000,
        maxAward: 15000000,
        naicsCodes: ['541512', '541715', '336411', '336413', '336414', '334511'],
        keywords: [
          'stratfi',
          'tacfi',
          'strategic funding increase',
          'tactical funding increase',
          'phase ii bridge',
          'matching funds',
          'program of record',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.spacewerx.us/stratfi-tacfi/',
        provenance: {
          sourceUrl: 'https://www.spacewerx.us/stratfi-tacfi/',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; the AFWERX STRATFI/TACFI page did not resolve at verification time, so the SpaceWERX page for the same vehicles is linked. SBIR contribution band $3M-$15M per our research reference; total packages can be larger with match.',
        },
      },
      {
        sourceId: 'seed-dhs-st-sbir',
        source: 'seed',
        title: 'DHS Science and Technology Directorate SBIR',
        description:
          'The DHS Science and Technology Directorate runs a small, focused SBIR program aimed at homeland security operational needs. Recurring topic areas include cybersecurity for operational technology and internet-of-things devices, software supply chain and SBOM tooling, AI-based threat detection, border and port security sensing, and first-responder technology. Solicitations emphasize deployability in a real security operations environment, and evaluators weigh practical measures such as false-positive rates. DHS also offers support aimed at first-time SBIR applicants.',
        agency: 'U.S. Department of Homeland Security',
        agencyCode: 'DHS',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        naicsCodes: ['541512', '541519', '541690', '541511', '561621'],
        keywords: [
          'cybersecurity',
          'operational technology',
          'internet of things',
          'sbom',
          'software supply chain',
          'threat detection',
          'critical infrastructure',
          'first responder',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.dhs.gov/science-and-technology/sbir',
        provenance: {
          sourceUrl: 'https://www.dhs.gov/science-and-technology/sbir',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov solicitations API was 403 during maintenance. Award amounts omitted because our research reference documents no DHS-specific figure.',
        },
      },
      {
        sourceId: 'seed-epa-sbir',
        source: 'seed',
        title: 'EPA SBIR Program',
        description:
          'The Environmental Protection Agency funds small businesses developing commercial technologies that address environmental problems. Recurring topic areas include clean and safe water, drinking water treatment and monitoring, air quality sensing, land revitalization and remediation, sustainable materials and manufacturing, and homeland security related environmental response. Awards are contracts, with a short Phase I feasibility effort followed by a competitive Phase II for commercialization-ready projects. Proposals are expected to show both environmental benefit and a commercial market.',
        agency: 'U.S. Environmental Protection Agency',
        agencyCode: 'EPA',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        naicsCodes: ['541620', '221310', '221320', '334513', '334511', '541360', '562910'],
        keywords: [
          'water quality',
          'drinking water',
          'water treatment',
          'air quality',
          'environmental sensors',
          'remediation',
          'sustainable manufacturing',
          'clean technology',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.epa.gov/sbir',
        provenance: {
          sourceUrl: 'https://www.epa.gov/sbir',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov was 403 during maintenance. Award amounts omitted because our research reference documents no EPA-specific figure.',
        },
      },
      {
        sourceId: 'seed-doe-sbir-phase-i',
        source: 'seed',
        title: 'DOE SBIR/STTR — Phase I',
        description:
          'The Department of Energy Office of Science runs SBIR and STTR across the full DOE mission: grid modernization, energy storage, advanced manufacturing and materials, water and energy efficiency, nuclear and fusion technology, environmental management, and scientific instrumentation. Topics are published in a detailed annual topics document, and each topic names the sponsoring DOE program office. DOE issues its SBIR/STTR awards as grants rather than contracts. A letter of intent is typically required before the full Phase I application.',
        agency: 'U.S. Department of Energy',
        agencyCode: 'DOE',
        fundingInstrument: 'grant',
        applicantTypeCodes: ['23'],
        aln: '81.049',
        alnAll: ['81.049'],
        alnResolved: true,
        isSbir: true,
        isSttr: true,
        programPhase: 'I',
        maxAward: 200000,
        naicsCodes: ['541715', '334513', '334511', '541620', '221310', '541690'],
        keywords: [
          'energy',
          'grid modernization',
          'energy storage',
          'water security',
          'sensors',
          'advanced manufacturing',
          'scientific instrumentation',
          'efficiency',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://science.osti.gov/sbir',
        provenance: {
          sourceUrl: 'https://science.osti.gov/sbir',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov was 403 during maintenance. Phase I ceiling ~$200K per our research reference; Phase II amounts omitted because no figure is documented there. ALN 81.049 is the DOE Office of Science financial assistance listing under which SBIR/STTR grants are made - verify on SAM.gov before relying on it as a join key.',
        },
      },
      {
        sourceId: 'seed-doe-ammto',
        source: 'seed',
        title: 'DOE Advanced Materials and Manufacturing Technologies Office (AMMTO)',
        description:
          'AMMTO funds research, development, and demonstration of advanced materials and manufacturing processes that improve energy efficiency and strengthen domestic manufacturing supply chains. Program areas include next-generation materials, lightweighting, high-performance composites and alloys, additive and hybrid manufacturing processes, smart and connected manufacturing, and critical materials recovery. Funding is issued through periodic funding opportunity announcements, often with cost-share and multi-partner teaming requirements. Small businesses typically participate either as a prime on an open funding opportunity or as a partner on a larger team.',
        agency: 'U.S. Department of Energy',
        agencyCode: 'DOE',
        fundingInstrument: 'grant',
        alnResolved: false,
        naicsCodes: ['541715', '326199', '336412', '336413'],
        keywords: [
          'advanced manufacturing',
          'advanced materials',
          'lightweighting',
          'composites',
          'additive manufacturing',
          'critical materials',
          'supply chain',
          'cost share',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://www.energy.gov/eere/ammto',
        provenance: {
          sourceUrl: 'https://www.energy.gov/eere/ammto',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record for an office-level funding program, seeded because open AMMTO announcements were not retrievable at seed time. Not restricted to small business, so no applicant-type restriction is asserted. Award amounts and dates omitted - they vary by announcement and none is documented in our research reference.',
        },
      },
      {
        sourceId: 'seed-ed-ies-sbir',
        source: 'seed',
        title: 'ED/IES SBIR (Institute of Education Sciences)',
        description:
          'The Institute of Education Sciences at the Department of Education funds small businesses to develop and evaluate education technology products for students, teachers, and administrators. Every award requires a genuine research component: a Phase I prototype with usability and feasibility testing, and a Phase II pilot study that measures learning, engagement, or educator-workload outcomes. Recent solicitations have emphasized workforce readiness, special education, and AI that reduces educator workload. Products that are purely transactional, such as booking or marketplace software with no instructional research core, are outside the program.',
        agency: 'U.S. Department of Education',
        agencyCode: 'ED',
        fundingInstrument: 'contract',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        isSbir: true,
        minAward: 250000,
        maxAward: 1000000,
        naicsCodes: ['541511', '541512', '513210'],
        keywords: [
          'education technology',
          'edtech',
          'learning outcomes',
          'pilot study',
          'usability testing',
          'workforce readiness',
          'special education',
          'educator workload',
        ],
        status: 'posted',
        curated: true,
        programUrl: 'https://ies.ed.gov/sbir',
        provenance: {
          sourceUrl: 'https://ies.ed.gov/sbir',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record; sbir.gov was 403 during maintenance. Amounts $250K Phase I / $1M Phase II per our research reference. The annual solicitation is a fall cycle but no exact date is documented there, so no close date is recorded.',
        },
      },
      {
        sourceId: 'seed-nist-mep',
        source: 'seed',
        title: 'NIST Manufacturing Extension Partnership (MEP)',
        description:
          'MEP is a NIST program that funds a center in every state to deliver hands-on technical assistance to small and mid-sized manufacturers. Services include process and quality improvement, supply chain development, workforce training, cybersecurity readiness for defense suppliers, and help adopting automation and advanced manufacturing methods. Manufacturers engage the state center directly and typically pay a subsidized fee rather than receiving a cash award. This is advisory and technical assistance capacity, not a funding instrument.',
        agency: 'National Institute of Standards and Technology',
        agencyCode: 'DOC-NIST',
        fundingInstrument: 'other',
        aln: '11.611',
        alnAll: ['11.611'],
        alnResolved: true,
        naicsCodes: ['336411', '336412', '336413', '326199'],
        keywords: [
          'manufacturing extension',
          'small manufacturer',
          'process improvement',
          'supply chain',
          'quality systems',
          'cybersecurity readiness',
          'automation',
          'technical assistance',
        ],
        status: 'posted',
        placement: 'alongside',
        curated: true,
        programUrl: 'https://www.nist.gov/mep',
        provenance: {
          sourceUrl: 'https://www.nist.gov/mep',
          verifiedAt: '2026-08-14',
          verifiedBy: 'planning-probe',
          note: 'Curated program record. Non-financial technical assistance, so it is placed alongside funding rather than as a funding award; no award amounts are asserted. ALN 11.611 is the published Manufacturing Extension Partnership assistance listing.',
        },
      },
      {
        sourceId: 'seed-gsa-mas-it',
        source: 'seed',
        title: 'GSA Multiple Award Schedule (MAS) — Information Technology Category',
        description:
          'The GSA Multiple Award Schedule is the federal government\'s primary contract vehicle for buying commercial products and services, including the IT Category covering software, cloud, cybersecurity, and IT professional services. Getting "on schedule" pre-negotiates pricing and terms once, so any federal agency can then issue a task order directly rather than running a fresh competition. This is the standard on-ramp for a company that wants the government as a paying customer rather than a research funder — no R&D component is required, but building a past-performance record and getting a facility/personnel security posture in order both help win task orders.',
        agency: 'U.S. General Services Administration',
        agencyCode: 'GSA',
        fundingInstrument: 'procurement',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        naicsCodes: ['541512', '541519', '541690', '561621'],
        keywords: [
          'gsa schedule',
          'multiple award schedule',
          'government contract vehicle',
          'federal marketplace',
          'it category',
          'task order',
          'government customer',
          'past performance',
        ],
        status: 'posted',
        placement: 'alongside',
        curated: true,
        programUrl: 'https://www.gsa.gov/buying-selling/products-services/get-on-a-schedule',
        provenance: {
          sourceUrl: 'https://www.gsa.gov/buying-selling/products-services/get-on-a-schedule',
          verifiedAt: '2026-08-15',
          verifiedBy: 'planning-probe',
          note: 'Curated program record for a procurement contract vehicle, not a funding award — no award amounts are asserted since GSA negotiates ceiling pricing per schedule holder, not a single award figure. NAICS scoped to the IT/technical-consulting category rather than general software development to avoid surfacing this for companies with no plausible government-agency customer.',
        },
      },
      {
        sourceId: 'seed-diu-cso',
        source: 'seed',
        title: 'DIU Commercial Solutions Opening (CSO)',
        description:
          'The Defense Innovation Unit runs a standing Commercial Solutions Opening that lets a company propose an existing or near-term commercial technology against a published defense problem statement, rather than responding to a traditional FAR-based solicitation. A successful pitch leads to an Other Transaction prototype agreement, typically resolved in months rather than the year-plus timeline of a conventional defense contract, with a path to a follow-on production contract if the prototype works. This is a procurement/commercialization pathway, not an R&D grant — DIU is explicitly looking for technology that already works and needs a defense customer, not early-stage research.',
        agency: 'U.S. Department of Defense (Defense Innovation Unit)',
        agencyCode: 'DOD',
        fundingInstrument: 'procurement',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        naicsCodes: ['336411', '336413', '336414', '541512', '541519', '541715'],
        keywords: [
          'diu',
          'commercial solutions opening',
          'other transaction agreement',
          'prototype contract',
          'defense customer',
          'dual-use',
          'follow-on production',
        ],
        status: 'posted',
        placement: 'alongside',
        curated: true,
        programUrl: 'https://www.diu.mil/work-with-us',
        provenance: {
          sourceUrl: 'https://www.diu.mil/work-with-us',
          verifiedAt: '2026-08-15',
          verifiedBy: 'planning-probe',
          note: 'Curated program record for a standing commercial-technology contracting pathway. No award band is asserted — CSO prototype agreement values vary by problem statement and are not published as a fixed range.',
        },
      },
      {
        sourceId: 'seed-sbir-phase3-sole-source',
        source: 'seed',
        title: 'SBIR/STTR Phase III Sole-Source Contract Authority',
        description:
          "Federal law (15 U.S.C. 638(r)) lets any agency award a follow-on contract for work that derives from a company's SBIR or STTR research without running a new competition, as long as the work is a continuation of that R&D. In practice this is the fastest path from a completed SBIR/STTR Phase I or Phase II into a paying government contract: an agency that already funded and evaluated the R&D can move straight to buying the resulting product or service instead of restarting a procurement from scratch. Eligibility depends on having a real, completed SBIR/STTR award to point to as the derivation — this is not a standalone program to apply to cold.",
        agency: 'Multiple federal agencies (authority applies government-wide)',
        agencyCode: 'SBA',
        fundingInstrument: 'procurement',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        naicsCodes: ['541511', '541512', '541715', '336411', '336413', '336414', '334511', '334513', '541620'],
        keywords: [
          'phase iii',
          'sole source',
          'sole-source authority',
          'follow-on contract',
          'sbir phase iii',
          'noncompetitive award',
          'commercialization',
        ],
        status: 'posted',
        placement: 'alongside',
        curated: true,
        programUrl: 'https://www.sbir.gov/tutorials/phase-iii',
        provenance: {
          sourceUrl: 'https://www.sbir.gov/tutorials/phase-iii',
          verifiedAt: '2026-08-15',
          verifiedBy: 'planning-probe',
          note: 'Curated record for a statutory authority rather than a solicitation. No award band is asserted since Phase III contract values are agency- and project-specific. NAICS spans every SBIR-eligible vertical already in this corpus (health, aerospace, water/energy, cyber) because the authority itself is agency-agnostic and contingent only on a prior SBIR/STTR award, not on industry.',
        },
      },
      {
        sourceId: 'seed-ota-prototype',
        source: 'seed',
        title: 'DoD Other Transaction Authority (OTA) — Prototype Projects',
        description:
          'Other Transaction agreements let the Department of Defense contract for prototype projects outside the standard Federal Acquisition Regulation, which means faster awards, negotiated (rather than FAR-standard) terms, and room for non-traditional defense contractors and startups to participate without a full FAR-compliant infrastructure in place. OTAs are most often issued through a consortium that already holds a master agreement with a DoD component, or directly by a program office running its own OTA solicitation. A completed OTA prototype that is successfully demonstrated can be moved to a follow-on production contract without a new competition.',
        agency: 'U.S. Department of Defense',
        agencyCode: 'DOD',
        fundingInstrument: 'procurement',
        applicantTypeCodes: ['23'],
        alnResolved: false,
        naicsCodes: ['336411', '336413', '336414', '541512', '541519', '541715'],
        keywords: [
          'other transaction authority',
          'ota',
          'prototype project',
          'non-traditional contractor',
          'consortium',
          'follow-on production',
          'defense innovation',
        ],
        status: 'posted',
        placement: 'alongside',
        curated: true,
        programUrl: 'https://www.acquisition.gov/OTA',
        provenance: {
          sourceUrl: 'https://www.acquisition.gov/OTA',
          verifiedAt: '2026-08-15',
          verifiedBy: 'planning-probe',
          note: 'Curated record for a contracting authority, not a single program. No award band or close date asserted — OTA prototype values and timelines are set per solicitation or per consortium master agreement, not by the authority itself. No specific consortium is named to avoid asserting membership terms we have not verified.',
        },
      },
    ];
  }
}
