export class UtahProgramsHelper {
  public static getSeedPrograms(): Record<string, unknown>[] {
    return [
      {
        sourceId: 'utif-microgrant',
        source: 'utah',
        title: 'UTIF Microgrant — First-Time SBIR/STTR Applicant',
        description:
          'Up to $3,000 for first-time SBIR/STTR Phase I applicants in Utah to offset proposal preparation costs.',
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'grant',
        applicantTypeCodes: ['23'],
        minAward: 3000,
        maxAward: 3000,
        status: 'posted',
        alnResolved: false,
        placement: 'alongside',
        programUrl: 'https://business.utah.gov/programs/utif/',
      },
      {
        sourceId: 'utif-bridge-loan',
        source: 'utah',
        title: 'UTIF Non-Recourse Bridge Loan',
        description:
          'Non-recourse loans of $50K–$60K for Utah SBIR/STTR Phase I winners. Repay only on commercial success.',
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'loan',
        applicantTypeCodes: ['23'],
        minAward: 50000,
        maxAward: 60000,
        status: 'posted',
        alnResolved: false,
        placement: 'alongside',
        programUrl: 'https://business.utah.gov/programs/utif/',
      },
      {
        sourceId: 'ssbci-utah',
        source: 'utah',
        title: 'Utah SSBCI — State Small Business Credit Initiative',
        description:
          '~$69M Utah allocation for small businesses. Includes set-asides for <10-employee businesses and disadvantaged entrepreneurs. Bridge loan program via WCF Insurance Foundation.',
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'loan',
        applicantTypeCodes: ['23'],
        minAward: 10000,
        maxAward: 5000000,
        status: 'posted',
        alnResolved: false,
        placement: 'non-grant',
        programUrl: 'https://business.utah.gov/programs/ssbci/',
      },
      {
        sourceId: 'sba-7a',
        source: 'utah',
        title: 'SBA 7(a) Loan Guarantee',
        description:
          "SBA's flagship loan guarantee up to $5M. For businesses that can't get conventional financing. Bank lends, SBA guarantees up to 85%.",
        agency: 'U.S. Small Business Administration',
        agencyCode: 'SBA',
        fundingInstrument: 'loan',
        applicantTypeCodes: ['23'],
        minAward: 50000,
        maxAward: 5000000,
        status: 'posted',
        alnResolved: false,
        placement: 'non-grant',
        programUrl: 'https://www.sba.gov/funding-programs/loans/7a-loans',
      },
      {
        sourceId: 'utah-apex',
        source: 'utah',
        title: 'Utah APEX Accelerator (formerly PTAC)',
        description:
          'Free federal procurement help for Utah small businesses. Assistance with SBIR/STTR applications, SAM.gov registration, and government contracting.',
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'other',
        applicantTypeCodes: ['23'],
        minAward: 0,
        maxAward: 0,
        status: 'posted',
        alnResolved: false,
        placement: 'alongside',
        programUrl: 'https://utahapex.org/',
      },
      {
        sourceId: 'nucleus-utah',
        source: 'utah',
        title: 'Nucleus (Utah Innovation Center) — Free SBIR/STTR Counseling',
        description:
          "Free SBIR/STTR proposal counseling from Utah's SBA FAST-award awardee. Utah has one of the highest federal R&D acceptance rates in the US (~15–17%).",
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'other',
        applicantTypeCodes: ['23'],
        minAward: 0,
        maxAward: 0,
        status: 'posted',
        alnResolved: false,
        placement: 'alongside',
        programUrl: 'https://business.utah.gov/nucleus/',
      },
      {
        sourceId: 'edtif-utah',
        source: 'utah',
        title: 'EDTIF — Economic Development Tax Increment Financing',
        description:
          'Utah tax rebate program for qualifying companies that create high-paying jobs. Post-performance rebate on new state taxes generated.',
        agency: "Utah Governor's Office of Economic Opportunity",
        agencyCode: 'GOEO',
        fundingInstrument: 'other',
        applicantTypeCodes: ['23'],
        status: 'posted',
        alnResolved: false,
        placement: 'alongside',
        programUrl: 'https://business.utah.gov/programs/edtif/',
      },
    ];
  }
}
