export interface ICoverageTarget {
  key: string;
  label: string;
  priority: 'must' | 'should';
  cases: number[];
  matchTitle: string[];
  matchAgency?: string[];
}

export const COVERAGE_TARGETS: ICoverageTarget[] = [
  {
    key: 'nih-sbir',
    label: 'NIH SBIR/STTR',
    priority: 'must',
    cases: [1],
    matchTitle: ['sbir', 'sttr', 'small business innovation research', 'small business technology'],
    matchAgency: ['national institutes of health', 'nih', 'hhs'],
  },
  {
    key: 'ahrq-health-services',
    label: 'AHRQ Health Services / Patient Safety',
    priority: 'should',
    cases: [1],
    matchTitle: ['patient safety', 'health services research', 'healthcare delivery', 'ahrq'],
    matchAgency: ['agency for healthcare research', 'ahrq'],
  },
  {
    key: 'arpa-h',
    label: 'ARPA-H Digital Health',
    priority: 'should',
    cases: [1],
    matchTitle: ['arpa-h', 'advanced research projects agency for health'],
  },
  {
    key: 'nasa-sbir',
    label: 'NASA SBIR/STTR',
    priority: 'must',
    cases: [2],
    matchTitle: ['sbir', 'sttr', 'small business innovation research'],
    matchAgency: ['national aeronautics', 'nasa'],
  },
  {
    key: 'dod-sbir',
    label: 'DoD SBIR/STTR (DSIP)',
    priority: 'must',
    cases: [2, 4],
    matchTitle: ['sbir', 'sttr', 'small business innovation research'],
    matchAgency: [
      'department of defense',
      'defense',
      'dod',
      'air force',
      'usaf',
      'navy',
      'army',
      'darpa',
    ],
  },
  {
    key: 'afwerx-open-topic',
    label: 'AFWERX Open Topic SBIR',
    priority: 'must',
    cases: [2, 4],
    matchTitle: ['afwerx', 'open topic'],
  },
  {
    key: 'spacewerx',
    label: 'SpaceWERX (Space Force)',
    priority: 'should',
    cases: [2],
    matchTitle: ['spacewerx', 'space force', 'orbital prime'],
  },
  {
    key: 'stratfi-tacfi',
    label: 'STRATFI / TACFI Bridge',
    priority: 'must',
    cases: [2],
    matchTitle: [
      'stratfi',
      'tacfi',
      'strategic funding increase',
      'tactical funding increase',
      'strategic and tactical funding',
    ],
  },
  {
    key: 'nist-mep',
    label: 'NIST MEP',
    priority: 'must',
    cases: [2],
    matchTitle: ['manufacturing extension partnership', 'nist mep'],
  },
  {
    key: 'doe-ammto',
    label: 'DOE AMMTO Advanced Manufacturing',
    priority: 'should',
    cases: [2],
    matchTitle: ['ammto', 'advanced materials and manufacturing', 'advanced manufacturing'],
    matchAgency: ['department of energy', 'energy', 'doe'],
  },
  {
    key: 'nsf-sbir',
    label: "NSF SBIR (America's Seed Fund)",
    priority: 'must',
    cases: [1, 3, 4],
    matchTitle: ['sbir', 'sttr', "america's seed fund", 'small business innovation research'],
    matchAgency: ['national science foundation', 'nsf'],
  },
  {
    key: 'epa-sbir',
    label: 'EPA SBIR',
    priority: 'must',
    cases: [3],
    matchTitle: ['sbir', 'small business innovation research'],
    matchAgency: ['environmental protection', 'epa'],
  },
  {
    key: 'doe-sbir',
    label: 'DOE SBIR/STTR',
    priority: 'should',
    cases: [3],
    matchTitle: ['sbir', 'sttr', 'small business innovation research'],
    matchAgency: ['department of energy', 'energy', 'doe'],
  },
  {
    key: 'reclamation-water',
    label: 'Reclamation WaterSMART / Prizes',
    priority: 'should',
    cases: [3],
    matchTitle: [
      'watersmart',
      'water and energy efficiency',
      'applied science grants',
      'prize competition',
      'reclamation',
    ],
    matchAgency: ['bureau of reclamation', 'reclamation', 'doi'],
  },
  {
    key: 'dhs-st-sbir',
    label: 'DHS S&T SBIR',
    priority: 'must',
    cases: [4],
    matchTitle: ['sbir', 'small business innovation research', 'science and technology'],
    matchAgency: ['homeland security', 'dhs'],
  },
  {
    key: 'ed-ies-sbir',
    label: 'ED/IES SBIR (edtech)',
    priority: 'must',
    cases: [5],
    matchTitle: ['sbir', 'small business innovation research'],
    matchAgency: ['department of education', 'institute of education sciences', 'ed'],
  },
  {
    key: 'sba-loans',
    label: 'SBA 7(a) / Microloan',
    priority: 'must',
    cases: [5],
    matchTitle: ['7(a)', 'microloan', 'loan guarantee'],
    matchAgency: ['small business administration', 'sba'],
  },
  {
    key: 'utah-ssbci',
    label: 'Utah SSBCI',
    priority: 'must',
    cases: [5],
    matchTitle: ['ssbci', 'state small business credit'],
  },
  {
    key: 'utah-utif',
    label: 'Utah UTIF Microgrant / Bridge Loan',
    priority: 'should',
    cases: [5],
    matchTitle: ['utif', 'utah technology innovation'],
  },
];
