export const INDUSTRY_SLUG_ALIASES: Record<string, string> = {
  'ai-healthcare': 'health-it',
  'health': 'health-it',
  'health-tech': 'health-it',
  'healthtech': 'health-it',
  'digital-health': 'health-it',
  'medical': 'health-it',
  'medtech': 'health-it',
  'biotech': 'health-it',
  'life-sciences': 'health-it',
  'clinical': 'health-it',
  'nursing': 'health-it',
  'hospital': 'health-it',
  'space': 'aerospace',
  'defense': 'aerospace',
  'advanced-manufacturing': 'manufacturing',
  'hardware': 'manufacturing',
  'composites': 'manufacturing',
  'additive': 'manufacturing',
  'materials': 'manufacturing',
  'launch': 'aerospace',
  'satellite': 'aerospace',
  'water-tech': 'water',
  'watertech': 'water',
  'wastewater': 'water',
  'sensors': 'water',
  'cleantech': 'climate',
  'energy': 'climate',
  'sustainability': 'climate',
  'environment': 'environmental',
  'cyber': 'cybersecurity',
  'security': 'cybersecurity',
  'infosec': 'cybersecurity',
  'threat-detection': 'cybersecurity',
  'marketplace': 'other',
  'consumer': 'other',
  'consumer-marketplace': 'other',
  'workforce': 'education',
  'youth': 'education',
  'learning': 'edtech',
  'platform': 'software',
  'saas-platform': 'saas',
  'machine-learning': 'ai',
  'artificial-intelligence': 'ai',
};

export const VERTICAL_AGENCY_PREFIXES: Record<string, string[]> = {
  'health-it': ['93', '47'],
  healthcare: ['93', '47'],
  aerospace: ['43', '12', '81', '11'],
  manufacturing: ['43', '12', '81', '11'],
  water: ['66', '15', '81', '47', '10'],
  climate: ['66', '15', '81', '47'],
  environmental: ['66', '15', '81', '47'],
  cybersecurity: ['12', '97', '47'],
  software: ['47', '12', '93'],
  saas: ['47', '12', '93'],
  ai: ['47', '12', '93'],
  education: ['84', '47'],
  edtech: ['84', '47'],
  other: ['47', '59', '84', '93'],
};

export const STOPWORDS: Set<string> = new Set([
  'the',
  'and',
  'for',
  'with',
  'that',
  'this',
  'need',
  'needs',
  'from',
  'our',
  'their',
  'have',
  'has',
  'are',
  'was',
  'will',
  'can',
  'use',
  'using',
  'into',
  'more',
  'than',
  'them',
  'they',
  'about',
  'company',
  'startup',
  'business',
  'utah',
  'million',
  'raised',
  'revenue',
  'employees',
  'growth',
  'expansion',
  'funding',
  'capital',
]);
