export const HISTORICAL_QUERY = {
  collection: 'corpus',
  source: 'usaspending',
  status: 'closed',
  scanLimit: 1500,
  cacheTtlMs: 300_000,
};

export const HISTORICAL_EVIDENCE_THRESHOLDS = {
  minimumScopedAwards: 3,
  maximumNamedWinners: 5,
};

export const AWARD_SANITY_BAND = {
  minimumAward: 25_000,
  maximumAward: 5_000_000,
};

export const UTAH_SCOPED_AWARD_SOURCES: string[] = ['usaspending'];

export const MEGAPRIME_RECIPIENT_BLOCKLIST: string[] = [
  'lockheed',
  'northrop',
  'grumman',
  'boeing',
  'raytheon',
  'rtx corporation',
  'general dynamics',
  'l3harris',
  'l-3 communications',
  'leidos',
  'booz allen',
  'science applications international',
  'huntington ingalls',
  'bae systems',
  'honeywell',
  'textron',
  'jacobs engineering',
  'caci',
  'mantech',
  'peraton',
  'aecom',
  'amentum',
  'parsons corporation',
  'kbr inc',
  'aerojet',
  'rocketdyne',
  'collins aerospace',
  'pratt & whitney',
  'pratt and whitney',
  'sierra nevada corporation',
  'spacex',
  'space exploration technologies',
  'palantir',
  'anduril',
  'deloitte',
  'accenture',
  'booz',
  'international business machines',
  'ibm corporation',
  'microsoft corporation',
  'amazon web services',
  'amazon.com',
  'google llc',
  'oracle america',
  'dell marketing',
  'dell federal',
  'hewlett packard',
  'at&t',
  'verizon',
  'general electric',
  'ge aviation',
  'siemens',
  'thermo fisher',
  'medtronic',
  'becton',
  'pfizer',
  'merck sharp',
  'johnson & johnson',
  'moderna',
  'mckesson',
  'unitedhealth',
  'lockheed martin',
  'battelle memorial',
  'mitre corporation',
];

export const NON_COMPANY_RECIPIENT_MARKERS: string[] = [
  'university',
  'universidad',
  'college',
  'school district',
  'board of',
  'regents',
  'trustees',
  'state of ',
  'city of ',
  'county of ',
  'town of ',
  'department of',
  'division of',
  'office of',
  'bureau of',
  'authority',
  'municipal',
  'conservancy',
  'foundation',
  'nonprofit',
  'non-profit',
  'institute',
  'association',
  'society',
  'council',
  'academy of',
  'church',
  'corporation of the president',
  'government',
  'agency',
  'hospital',
  'health system',
];

export const RECIPIENT_NAME_ACRONYMS: string[] = [
  'llc',
  'l.l.c.',
  'lp',
  'llp',
  'pllc',
  'pc',
  'usa',
  'ai',
  'it',
  'rf',
  'uav',
  'uas',
  '3d',
  'led',
  'r&d',
];

export const RECIPIENT_NAME_LEGAL_SUFFIXES: string[] = [
  'inc',
  'inc.',
  'co',
  'co.',
  'corp',
  'corp.',
  'ltd',
  'ltd.',
  'dba',
  'the',
  'and',
  'of',
];

export const RECIPIENT_NAME_SHORT_TOKEN_LENGTH = 4;

export const AGENCY_STOPWORD_TOKENS: string[] = [
  'department',
  'departments',
  'of',
  'the',
  'and',
  'for',
  'us',
  'u.s.',
  'united',
  'states',
  'office',
  'offices',
  'administration',
  'agency',
  'national',
  'federal',
  'bureau',
  'division',
  'center',
  'centers',
  'institutes',
  'institute',
  'service',
  'services',
  'program',
  'programs',
  'command',
];

export const DIRECTORY_INDUSTRY_TO_VERTICAL_SLUGS: Record<string, string[]> = {
  'aerospace and defense': ['aerospace', 'manufacturing', 'cybersecurity'],
  agriculture: ['other'],
  'arts and entertainment and recreation': ['other'],
  'consumer packaged goods': ['other'],
  'financial services': ['other'],
  'hospitality and food services': ['other'],
  'life sciences and healthcare': ['health-it', 'healthcare'],
  manufacturing: ['manufacturing', 'aerospace', 'water', 'climate', 'environmental'],
  other: ['other', 'water', 'climate', 'environmental', 'education', 'edtech'],
  'software and information technology': ['software', 'saas', 'ai', 'cybersecurity', 'health-it', 'edtech'],
};

export const VERTICAL_SLUG_TO_DIRECTORY_INDUSTRIES: Record<string, string[]> = {
  'health-it': ['Life Sciences and Healthcare', 'Software and Information Technology'],
  healthcare: ['Life Sciences and Healthcare'],
  aerospace: ['Aerospace and Defense', 'Manufacturing'],
  manufacturing: ['Manufacturing', 'Aerospace and Defense'],
  water: ['Manufacturing', 'Other'],
  climate: ['Manufacturing', 'Other'],
  environmental: ['Manufacturing', 'Other'],
  cybersecurity: ['Software and Information Technology', 'Aerospace and Defense'],
  software: ['Software and Information Technology'],
  saas: ['Software and Information Technology'],
  ai: ['Software and Information Technology'],
  education: ['Other'],
  edtech: ['Other', 'Software and Information Technology'],
  other: ['Other'],
};

export const VERTICAL_SLUG_LABELS: Record<string, string> = {
  'health-it': 'health-tech',
  healthcare: 'healthcare',
  aerospace: 'aerospace',
  manufacturing: 'advanced-manufacturing',
  water: 'water-tech',
  climate: 'climate-tech',
  environmental: 'environmental-tech',
  cybersecurity: 'cybersecurity',
  software: 'software',
  saas: 'software',
  ai: 'AI',
  education: 'education',
  edtech: 'edtech',
  other: 'early-stage',
};

export const DIRECTORY_STAGE_VOCABULARY: string[] = ['All Stages'];

export const DIRECTORY_NEED_VOCABULARY: string[] = ['capital', 'mentorship', 'space', 'customers', 'marketing', 'legal'];

export const PROFILE_NEED_TRIGGERS: Record<string, string[]> = {
  capital: ['fund', 'capital', 'grant', 'raise', 'runway', 'financing', 'loan', 'award'],
  mentorship: ['mentor', 'advis', 'coach', 'first-time', 'first time', 'guidance'],
  space: ['lab', 'facility', 'workshop', 'prototyp', 'manufactur', 'office space', 'cleanroom'],
  customers: ['customer', 'pilot', 'market', 'distribution', 'sales', 'procurement', 'contract'],
  marketing: ['brand', 'marketing', 'go-to-market', 'demand'],
  legal: ['legal', 'patent', 'ip ', 'intellectual property', 'compliance', 'incorporat'],
};

export const RESOURCE_MATCH_LIMITS = {
  maximumResults: 5,
  minimumRelevanceScore: 9,
  countyScore: 3,
  statewideScore: 2,
  industryScore: 2,
  needScore: 2,
  ruralBonus: 1,
  verticalBonus: 4,
  missingRdCorePenalty: 6,
  maximumPerCategory: 2,
};

export const RURAL_UTAH_COUNTIES: string[] = [
  'Beaver',
  'Box Elder',
  'Cache',
  'Carbon',
  'Daggett',
  'Duchesne',
  'Emery',
  'Garfield',
  'Grand',
  'Iron',
  'Juab',
  'Kane',
  'Millard',
  'Morgan',
  'Piute',
  'Rich',
  'San Juan',
  'Sanpete',
  'Sevier',
  'Summit',
  'Tooele',
  'Uintah',
  'Wasatch',
  'Washington',
  'Wayne',
];

export const UTAH_CITY_TO_COUNTY: Record<string, string> = {
  'salt lake city': 'Salt Lake',
  'west valley city': 'Salt Lake',
  'west jordan': 'Salt Lake',
  'south jordan': 'Salt Lake',
  sandy: 'Salt Lake',
  draper: 'Salt Lake',
  murray: 'Salt Lake',
  midvale: 'Salt Lake',
  millcreek: 'Salt Lake',
  holladay: 'Salt Lake',
  taylorsville: 'Salt Lake',
  riverton: 'Salt Lake',
  herriman: 'Salt Lake',
  bluffdale: 'Salt Lake',
  magna: 'Salt Lake',
  'cottonwood heights': 'Salt Lake',
  provo: 'Utah',
  orem: 'Utah',
  lehi: 'Utah',
  'american fork': 'Utah',
  'pleasant grove': 'Utah',
  lindon: 'Utah',
  vineyard: 'Utah',
  'spanish fork': 'Utah',
  springville: 'Utah',
  payson: 'Utah',
  'saratoga springs': 'Utah',
  'eagle mountain': 'Utah',
  alpine: 'Utah',
  highland: 'Utah',
  ogden: 'Weber',
  roy: 'Weber',
  'south ogden': 'Weber',
  layton: 'Davis',
  kaysville: 'Davis',
  farmington: 'Davis',
  bountiful: 'Davis',
  centerville: 'Davis',
  clearfield: 'Davis',
  syracuse: 'Davis',
  logan: 'Cache',
  'north logan': 'Cache',
  smithfield: 'Cache',
  'st george': 'Washington',
  'saint george': 'Washington',
  hurricane: 'Washington',
  ivins: 'Washington',
  'santa clara': 'Washington',
  'cedar city': 'Iron',
  'park city': 'Summit',
  heber: 'Wasatch',
  'heber city': 'Wasatch',
  tooele: 'Tooele',
  moab: 'Grand',
  vernal: 'Uintah',
  roosevelt: 'Duchesne',
  price: 'Carbon',
  'brigham city': 'Box Elder',
  tremonton: 'Box Elder',
  nephi: 'Juab',
  richfield: 'Sevier',
  ephraim: 'Sanpete',
  manti: 'Sanpete',
  delta: 'Millard',
  fillmore: 'Millard',
  kanab: 'Kane',
  blanding: 'San Juan',
  monticello: 'San Juan',
  beaver: 'Beaver',
  panguitch: 'Garfield',
  morgan: 'Morgan',
  coalville: 'Summit',
  'garden city': 'Rich',
};


export const RESOURCE_RELEVANCE_KEYWORDS: Record<
  string,
  {
    weight: number;
    category: string;
    reason: string;
    verticalSlugs?: string[];
    ownershipSignals?: string[];
    requiresRdCore?: boolean;
  }
> = {
  'utah innovation center': {
    weight: 14,
    category: 'sbir-counseling',
    reason: 'Free SBIR/STTR counseling from the state innovation office, built for first-time federal applicants',
    requiresRdCore: true,
  },
  "utah governor's office of economic opportunity": {
    weight: 13,
    category: 'state-programs',
    reason: 'GOEO runs the state SBIR/STTR support programs, including microgrants for first-time Phase I applicants',
  },
  'apex accelerator': {
    weight: 12,
    category: 'procurement',
    reason: 'Free federal procurement help: SAM.gov registration, GSA Schedule and contract search',
  },
  'utah innovation fund': {
    weight: 12,
    category: 'capital',
    reason: 'State fund that backs Utah deep-tech companies commercializing research',
    requiresRdCore: true,
  },
  'small business development center': {
    weight: 11,
    category: 'advising',
    reason: 'No-cost business advising and proposal review through the statewide SBDC network',
  },
  sbdc: {
    weight: 11,
    category: 'advising',
    reason: 'No-cost business advising and proposal review through the statewide SBDC network',
  },
  'utah mep': {
    weight: 11,
    category: 'technical-assistance',
    reason: 'Manufacturing Extension Partnership: subsidized engineering, quality and process help for Utah manufacturers',
    verticalSlugs: ['manufacturing', 'aerospace', 'water', 'climate', 'environmental', 'other'],
  },
  'impact utah': {
    weight: 10,
    category: 'technical-assistance',
    reason: 'Utah MEP affiliate offering subsidized manufacturing and operations consulting',
    verticalSlugs: ['manufacturing', 'aerospace', 'water', 'climate', 'environmental', 'other'],
  },
  'small business credit initiative': {
    weight: 10,
    category: 'capital',
    reason: 'Utah SSBCI capital access: loan participation and credit support, including a set-aside for very small employers',
  },
  microloan: {
    weight: 10,
    category: 'capital',
    reason: 'Microloans up to $50K when a federal award timeline is too slow for payroll',
  },
  'revolving loan fund': {
    weight: 9,
    category: 'capital',
    reason: 'Regional revolving loan fund: non-dilutive debt for equipment and facilities',
  },
  '47g': {
    weight: 10,
    category: 'industry-network',
    reason: 'Utah aerospace and defense association, the fastest route to the DoD and NASA end users SBIR reviewers look for',
    verticalSlugs: ['aerospace', 'manufacturing', 'cybersecurity'],
  },
  'utah defense alliance': {
    weight: 9,
    category: 'industry-network',
    reason: 'Connects Utah companies to Hill AFB and other defense end users',
    verticalSlugs: ['aerospace', 'manufacturing', 'cybersecurity'],
  },
  biohive: {
    weight: 10,
    category: 'industry-network',
    reason: 'Utah life-sciences network with NIH-funded peers and clinical validation partners',
    verticalSlugs: ['health-it', 'healthcare'],
  },
  'bio utah': {
    weight: 9,
    category: 'industry-network',
    reason: 'Utah life-sciences trade association: clinical partners and regulatory contacts',
    verticalSlugs: ['health-it', 'healthcare'],
  },
  'utah manufacturers association': {
    weight: 8,
    category: 'industry-network',
    reason: 'Trade association for Utah manufacturers: supply-chain and workforce introductions',
    verticalSlugs: ['manufacturing', 'aerospace'],
  },
  'silicon slopes': {
    weight: 7,
    category: 'industry-network',
    reason: 'Utah tech community where founders who have already run federal pilots are easy to reach',
    verticalSlugs: ['software', 'saas', 'ai', 'cybersecurity', 'health-it', 'edtech'],
  },
  'sillicon slopes': {
    weight: 7,
    category: 'industry-network',
    reason: 'Utah tech community where founders who have already run federal pilots are easy to reach',
    verticalSlugs: ['software', 'saas', 'ai', 'cybersecurity', 'health-it', 'edtech'],
  },
  'small business administration': {
    weight: 9,
    category: 'capital',
    reason: 'SBA 7(a), 504 and microloan programs for the part of the need a grant will not cover',
  },
  'sba thrive': {
    weight: 7,
    category: 'advising',
    reason: 'SBA growth program for established small businesses preparing to scale',
  },
  score: {
    weight: 6,
    category: 'advising',
    reason: 'Free one-on-one mentoring from retired executives who have run federal proposals',
  },
  'world trade center utah': {
    weight: 7,
    category: 'export',
    reason: 'Export assistance and STEP grants if any of the revenue plan is international',
  },
  'commercial service': {
    weight: 6,
    category: 'export',
    reason: 'Federal export counseling and foreign-buyer introductions',
  },
  lassonde: {
    weight: 8,
    category: 'university',
    reason: 'University of Utah startup institute: labs, mentors and commercialization microgrants',
  },
  'rollins center': {
    weight: 7,
    category: 'university',
    reason: 'BYU entrepreneurship center: student research teams and commercialization mentoring',
  },
  'center for entrepreneurship': {
    weight: 6,
    category: 'university',
    reason: 'University entrepreneurship center offering advising and student research capacity',
  },
  'innovation center': {
    weight: 6,
    category: 'incubator',
    reason: 'Local innovation center with lab and office space plus hands-on startup coaching',
  },
  'innovation hub': {
    weight: 6,
    category: 'incubator',
    reason: 'Local innovation hub with lab and office space plus hands-on startup coaching',
  },
  'grow utah': {
    weight: 6,
    category: 'advising',
    reason: 'Statewide entrepreneur support with capital and mentorship connections',
  },
  'utah center for rural development': {
    weight: 7,
    category: 'state-programs',
    reason: 'Rural-focused funding and technical assistance for companies outside the Wasatch Front',
  },
  "women's business center": {
    weight: 8,
    category: 'community',
    reason: 'Women-owned business advising, certification help and capital readiness',
    ownershipSignals: ['women', 'women-owned', 'woman-owned', 'female-founded'],
  },
  'veteran business resource center': {
    weight: 8,
    category: 'community',
    reason: 'Veteran-owned business advising plus help claiming federal veteran set-asides',
    ownershipSignals: ['veteran', 'veteran-owned', 'service-disabled'],
  },
  'veteran-owned business registration': {
    weight: 7,
    category: 'community',
    reason: 'State veteran-owned registration that unlocks federal and state set-aside preferences',
    ownershipSignals: ['veteran', 'veteran-owned', 'service-disabled'],
  },
  'suazo business center': {
    weight: 7,
    category: 'community',
    reason: 'Bilingual advising and capital access for Latino and underserved founders',
    ownershipSignals: ['minority', 'minority-owned', 'latino', 'hispanic', 'underserved', 'disadvantaged'],
  },
};

export const RESOURCE_TITLE_EXCLUSIONS: string[] = [
  'event',
  'summit',
  'seminar',
  'conference',
  'tech week',
  'office space for rent',
  'coworking space',
  'home plans',
];
